name: dbas_sqlite_example
description: "Demonstrates how to use the dbas_sqlite plugin."
version: 1.0.0
homepage: https://github.com/dailysoftwaresystems/dbas_sqlite
publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.2.4
  dbas_sqlite:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
