name: dbas_sqlite_flutter_example
description: "Demonstrates how to use the dbas_sqlite_flutter plugin."
version: 1.0.0
homepage: https://github.com/dailysoftwaresystems/DBAS.SQLite.Flutter
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.2.4
  dbas_sqlite_flutter:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
