name: Test Flutter Plugin
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{github.workspace}}
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Auto set package version from pubspec.yaml
      run: |
        version=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)
        echo "Building version: $version"
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Get Flutter dependencies
      run: flutter pub get
    - name: Analyze code
      run: flutter analyze
    - name: Run Flutter tests
      run: flutter test
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        body: Release ${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
